libs =
#import libs += libhello%lib{hello}
import libs += libcrails-cli%lib{crails-cli}
import libs += libcrails-crontab%lib{crails-crontab}
import libs += libcrails-database-url%lib{crails-database-url}
import libs += libboost-program-options%lib{boost_program_options}

exe{crails-backup}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
